Created initial pipeline workflow foundation
BUMETCS673/seprojects-cs673olf24team6 pull request #12
Opened 2024-09-21 19:21 UTC by rzheng2019

An initial workflow foundation was created to implement the early stages of the overall pipeline.

2024-09-21 20:04 UTC, jshilts657 requested changes

2024-09-21 20:04 UTC, jshilts657 commented on .github/workflows/current-workflow.yml
> +      - dev
Don't we need the '**' here for all branches?

2024-09-21 20:04 UTC, jshilts657 commented on .github/workflows/current-workflow.yml
> +        run: pip install flask
it would actually be better to install using the requirements.txt file that way all the dependancies for flask and whatever else our application needs is installed as well
This would look like this 

`run: pip install -r requirements.txt`

2024-09-21 20:04 UTC, jshilts657 commented on .github/workflows/current-workflow.yml
> +        run: docker run --name created_container -d -p 5000:5000 flask-backend
5000:5000 is not required since the docker file has been updated to expose port 5000 on start up

2024-09-21 20:04 UTC, jshilts657 commented on .github/workflows/current-workflow.yml
> +        run: npm install react-scripts --save
should install npm before we install npm react--script i believe

2024-09-21 20:04 UTC, jshilts657 commented on .github/workflows/current-workflow.yml
> +        run: npm install react-scripts --save
I am realizing we also are missing the package-lock.json file 
We needs something like the command below in addition to the package-lock.json file being pushed up.
You should have one I think you just might need to remove the line package-lock.json from the .gitignore file

`run: npm ci`

2024-09-21 20:04 UTC, jshilts657 commented on .github/workflows/current-workflow.yml
> +
you need to make sure you kill npm services for a cleaner exit

run: pkill -f "npm start"

2024-09-22 20:11 UTC, jshilts657 approved these changes

2024-09-22 23:23 UTC, BlueGreenDragon approved these changes
Looks good.

2024-09-22 23:24 UTC, BlueGreenDragon approved these changes
Looks good.

2024-09-23 04:46 UTC, Rekik27 approved these changes
looks good

2024-09-23 15:54 UTC, jamzheng109 approved these changes
Everything looks good

2024-09-23 18:42 UTC, merged