Update README.md
BUMETCS673/seprojects-cs673olf24team6 pull request #13
Opened 2024-09-22 01:36 UTC by jshilts657

Readme updates
Updated tools and instructions on how to run the software

2024-09-22 19:40 UTC, rzheng2019 requested changes

2024-09-22 19:40 UTC, rzheng2019 commented on README.md
> +     a. To run the application using python use `npm start`
This should just be Node, not Python, when running the frontend application.

2024-09-22 19:40 UTC, rzheng2019 commented on README.md
> +      ii. docker run  -d -t front_end
Looks good, although there looks like an extra space between "run" and "-d"

2024-09-22 20:19 UTC, jshilts657 commented on README.md
> +     a. To run the application using python use `npm start`
Changed to Node

2024-09-22 20:20 UTC, jshilts657 commented on README.md
> +      ii. docker run  -d -t front_end
extra space removed
Also updated to use md format which  I forgot to do

2024-09-22 20:21 UTC, rzheng2019 approved these changes

2024-09-22 23:25 UTC, BlueGreenDragon approved these changes
Looks good.

2024-09-23 04:44 UTC, Rekik27 approved these changes
looks great

2024-09-23 12:02 UTC, merged