Data input fields
BUMETCS673/seprojects-cs673olf24team6 pull request #26
Opened 2024-10-01 22:51 UTC by acflinch

2024-10-01 23:42 UTC, BlueGreenDragon approved these changes
Looks good.

2024-10-02 00:23 UTC, jshilts657 requested changes
Just two small fixes,
Honestly my bad I should have caught them earlier

2024-10-02 00:23 UTC, jshilts657 commented on code/frontend/src/components/MovieQueryFormComponent.js
> +            rank : document.getElementById('rank').value;
you need to replace the ; -> ,

2024-10-02 00:23 UTC, jshilts657 commented on code/frontend/src/components/MovieQueryFormComponent.js
> +        }
add semi-colon at end  like };

2024-10-02 00:24 UTC, jshilts657 commented on code/frontend/src/components/MovieQueryFormComponent.js
> +            rank : document.getElementById('rank').value;
you need to do this for all elements in the json. 
Look at an example json object. each element is separated by a comma not a semi-colon

2024-10-03 00:13 UTC, jshilts657 approved these changes

2024-10-03 00:43 UTC, rzheng2019 requested changes
I was only able to run the tests when I changed the package.json testMatch path on line 16 to "<rootDir>/src/tests/*.test.js", the front slash next to the * needs to removed to grab all ".test.js" files

2024-10-03 01:00 UTC, rzheng2019 approved these changes
Looks good now.

2024-10-03 01:04 UTC, merged