Feature/pylint integration
BUMETCS673/seprojects-cs673olf24team6 pull request #27
Opened 2024-10-01 22:57 UTC by jamzheng109

new updated pylint.yml file

2024-10-01 22:59 UTC, acflinch approved these changes

2024-10-01 23:29 UTC, jshilts657 commented
You need to merge Ricky's branch into your branch
Then reset the PR to merge into dev not Ricky's branch

2024-10-02 00:46 UTC, jshilts657 commented on .github/workflows/current-workflow.yml
> +        run: docker pull rzheng2024/seprojects-cs673olf24team6:flask_backend
Yea this is definetly not the correct pipeline changes

2024-10-02 00:47 UTC, jshilts657 requested changes

2024-10-02 00:47 UTC, jshilts657 commented on .github/workflows/current-workflow.yml
> +        run: docker pull rzheng2024/seprojects-cs673olf24team6:flask_backend
THis is the correct branch 
feature/publish-workflow-images-to-GitHub-Package-Registry

2024-10-03 19:02 UTC, closed without merging