Feature/publish workflow images to GitHub package registry
BUMETCS673/seprojects-cs673olf24team6 pull request #28
Opened 2024-10-02 02:52 UTC by rzheng2019

Implemented publishing to GitHub Package registry for frontend and backend Docker images.

2024-10-02 03:48 UTC, BlueGreenDragon approved these changes
Looks good.

2024-10-02 16:40 UTC, jshilts657 requested changes
Just remove the stage and you are good to merge

I made the changes so that now we are using the branch name now now

2024-10-02 16:40 UTC, jshilts657 commented on .github/workflows/current-workflow.yml
>    Node-Service:
This stage is no longer needed and you may remove it .
There should be only four stages when this compelte

2024-10-02 18:14 UTC, jshilts657 approved these changes

2024-10-03 00:16 UTC, acflinch approved these changes

2024-10-03 01:01 UTC, merged