integrating pylint test for database
BUMETCS673/seprojects-cs673olf24team6 pull request #36
Opened 2024-10-08 22:35 UTC by jamzheng109

2024-10-09 12:46 UTC, jshilts657 approved these changes
Looks good

2024-10-10 00:27 UTC, rzheng2019 approved these changes
Looks good

2024-10-11 01:11 UTC, rzheng2019 requested changes

2024-10-11 01:11 UTC, rzheng2019 commented on .github/workflows/current-workflow.yml
> +      image: ghcr.io/bumetcs673/seprojects-cs673olf24team6/flask_backend:${{ needs.get-branch-name.outputs.sanitized_branch_name }}
This image path is for the flask_backend when it should be the sqlite_database

2024-10-14 00:37 UTC, jshilts657 reviewed
You need to merge dev and push up as soon as you are able

2024-10-15 03:44 UTC, closed without merging